### PR TITLE
WIP: Turning album into a package

### PR DESCRIPTION
**Pull request by ericdill**
- [ ] Need to sort out this NotADirectoryError

```
NotADirectoryError: [Errno 20] Not a directory: '/home/edill/miniconda/envs/album_test/lib/python3.4/site-packages/album-0.0.0+22.gea16024-py3.4.egg/album/templates/run_index.html'
```

### CODE REVIEW

**Comment by danielballan** [comment]
I suspect the issue is that templates is not a package (and it shouldn't be one). So `album.templates` fails. Maybe try `package_data={'album': ['templates/*.html']},`

**Comment by ericdill** [comment]
Ok, this branch works as a conda-recipe and with `python setup.py develop`. It does not work with `python setup.py install` due to issues with the .egg not being unzipped and the jinja templating engine expecting a plain file (not a pointer to one inside an archive)

```
plot = VBox, ViewModel:VBox, ref _id: 39433677-3e07-41a7-89c5-72a700b69f07
127.0.0.1 - - [18/Sep/2015 23:28:50] "GET /run/cc34ed4e-9e28-4e2d-b364-64c7b869fdd7 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/album-0+untagged.25.g5e9b78a-py3.4.egg/album/server.py", line 39, in run_show
    **bokeh_kw)
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/flask/templating.py", line 60, in get_source
    return loader.get_source(environment, local_name)
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/jinja2/loaders.py", line 171, in get_source
    f = open_if_exists(filename)
  File "/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/jinja2/utils.py", line 151, in open_if_exists
    return open(filename, mode)
NotADirectoryError: [Errno 20] Not a directory: '/Users/edill/mc/envs/nikea3/lib/python3.4/site-packages/album-0+untagged.25.g5e9b78a-py3.4.egg/album/templates/run_show.html'
```

**Comment by ericdill** [comment]
@danielballan this is probably good to go. If you agree, merge away and I will tag a v0.0.1

**Comment by ericdill** [comment]
If you'd like to give it a shot, `conda install -c ericdill album` then executing `album` at the command line should start the flask server.  Note that I built this on my macbook air so you should be able to run it on yours :)  Once tagged I will build linux binaries for distribution internally at the NSLS-II beamlines so we can start getting feedback!

**Comment by danielballan** [comment]
This works. We can deal with packaging details later. For the record, conda and python setup.py develop currently work.

**Pull request merged**
